import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const clubesEuropeus = []

adicionarElementoALista(clubesEuropeus, 'Barcelona', 'facil')
adicionarElementoALista(clubesEuropeus, 'Real Madrid', 'facil')
adicionarElementoALista(clubesEuropeus, 'Manchester United', 'facil')
adicionarElementoALista(clubesEuropeus, 'Liverpool', 'facil')
adicionarElementoALista(clubesEuropeus, 'Bayern Munich', 'facil')
adicionarElementoALista(clubesEuropeus, 'Paris Saint-Germain', 'facil')
adicionarElementoALista(clubesEuropeus, 'Juventus', 'facil')
adicionarElementoALista(clubesEuropeus, 'Chelsea', 'facil')
adicionarElementoALista(clubesEuropeus, 'AC Milan', 'facil')
adicionarElementoALista(clubesEuropeus, 'Manchester City', 'facil')
adicionarElementoALista(clubesEuropeus, 'Borussia Dortmund', 'medio')
adicionarElementoALista(clubesEuropeus, 'Atletico Madrid', 'medio')
adicionarElementoALista(clubesEuropeus, 'Inter Milan', 'medio')
adicionarElementoALista(clubesEuropeus, 'Tottenham Hotspur', 'medio')
adicionarElementoALista(clubesEuropeus, 'Arsenal', 'medio')
adicionarElementoALista(clubesEuropeus, 'Napoli', 'medio')
adicionarElementoALista(clubesEuropeus, 'Sevilla', 'medio')
adicionarElementoALista(clubesEuropeus, 'Porto', 'medio')
adicionarElementoALista(clubesEuropeus, 'Benfica', 'medio')
adicionarElementoALista(clubesEuropeus, 'AS Roma', 'medio')
adicionarElementoALista(clubesEuropeus, 'Atalanta', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Zenit St. Petersburg', 'dificil')
adicionarElementoALista(clubesEuropeus, 'RB Leipzig', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Villarreal', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Lazio', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Shakhtar Donetsk', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Lyon', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Monaco', 'dificil')
adicionarElementoALista(clubesEuropeus, 'Ajax', 'dificil')
adicionarElementoALista(clubesEuropeus, 'PSV Eindhoven', 'dificil')