import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const clubesBrasileiros = []

adicionarElementoALista(clubesBrasileiros, 'Flamengo', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Palmeiras', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Corinthians', 'facil')
adicionarElementoALista(clubesBrasileiros, 'São Paulo', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Santos', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Grêmio', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Internacional', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Cruzeiro', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Atlético Mineiro', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Vasco da Gama', 'facil')
adicionarElementoALista(clubesBrasileiros, 'Fluminense', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Botafogo', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Bahia', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Sport Recife', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Athletico Paranaense', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Ceará', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Fortaleza', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Coritiba', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Goiás', 'medio')
adicionarElementoALista(clubesBrasileiros, 'América Mineiro', 'medio')
adicionarElementoALista(clubesBrasileiros, 'Avaí', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Chapecoense', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Cuiabá', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Juventude', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Red Bull Bragantino', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Náutico', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Paysandu', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Figueirense', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Santa Cruz', 'dificil')
adicionarElementoALista(clubesBrasileiros, 'Vila Nova', 'dificil')