import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const jogadoresAposentados = []

adicionarElementoALista(jogadoresAposentados, 'Pelé', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Diego Maradona', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Zinedine Zidane', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Ronaldo Nazário', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Ronaldinho', 'facil')
adicionarElementoALista(jogadoresAposentados, 'David Beckham', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Franz Beckenbauer', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Paolo Maldini', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Thierry Henry', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Johan Cruyff', 'facil')
adicionarElementoALista(jogadoresAposentados, 'Roberto Carlos', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Andrea Pirlo', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Luis Figo', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Xavi Hernandez', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Francesco Totti', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Gabriel Batistuta', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Clarence Seedorf', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Kaka', 'medio')
adicionarElementoALista(jogadoresAposentados, 'George Best', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Didier Drogba', 'medio')
adicionarElementoALista(jogadoresAposentados, 'Gheorghe Hagi', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Hristo Stoichkov', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Rivaldo', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Fernando Redondo', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Enzo Francescoli', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Rui Costa', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Davor Suker', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Michael Laudrup', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Sócrates', 'dificil')
adicionarElementoALista(jogadoresAposentados, 'Gianfranco Zola', 'dificil')