import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const jogadoresEmAtividade = []

adicionarElementoALista(jogadoresEmAtividade, 'Lionel Messi', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Cristiano Ronaldo', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Neymar', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Kylian Mbappé', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Kevin De Bruyne', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Robert Lewandowski', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Mohamed Salah', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Harry Kane', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Virgil van Dijk', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Karim Benzema', 'facil')
adicionarElementoALista(jogadoresEmAtividade, 'Erling Haaland', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Bruno Fernandes', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Romelu Lukaku', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Jadon Sancho', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Sadio Mane', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Raheem Sterling', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Joshua Kimmich', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Luka Modric', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Thomas Muller', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Gianluigi Donnarumma', 'medio')
adicionarElementoALista(jogadoresEmAtividade, 'Josko Gvardiol', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Youssoufa Moukoko', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Pedri', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Rodrygo Goes', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Ferran Torres', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Matheus Cunha', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Federico Chiesa', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Florian Wirtz', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Ansu Fati', 'dificil')
adicionarElementoALista(jogadoresEmAtividade, 'Ryan Gravenberch', 'dificil')