import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const objetos = []
adicionarElementoALista(objetos, 'bola', 'facil')
adicionarElementoALista(objetos, 'trave', 'facil')
adicionarElementoALista(objetos, 'chuteira', 'facil')
adicionarElementoALista(objetos, 'camisa', 'facil')
adicionarElementoALista(objetos, 'cartão amarelo', 'facil')
adicionarElementoALista(objetos, 'cartão vermelho', 'facil')
adicionarElementoALista(objetos, 'apito', 'facil')
adicionarElementoALista(objetos, 'meião', 'facil')
adicionarElementoALista(objetos, 'bandeirinha', 'facil')
adicionarElementoALista(objetos, 'caneta', 'facil')
adicionarElementoALista(objetos, 'luva de goleiro', 'medio')
adicionarElementoALista(objetos, 'colete de treino', 'medio')
adicionarElementoALista(objetos, 'placar eletrônico', 'medio')
adicionarElementoALista(objetos, 'calção', 'medio')
adicionarElementoALista(objetos, 'tornozeleira', 'medio')
adicionarElementoALista(objetos, 'caneleira', 'medio')
adicionarElementoALista(objetos, 'spray de barreira', 'medio')
adicionarElementoALista(objetos, 'bola de treino', 'medio')
adicionarElementoALista(objetos, 'marca do pênalti', 'medio')
adicionarElementoALista(objetos, 'escanteio', 'medio')
adicionarElementoALista(objetos, 'bomba de inflar bola', 'dificil')
adicionarElementoALista(objetos, 'placar manual', 'dificil')
adicionarElementoALista(objetos, 'bandeira de escanteio', 'dificil')
adicionarElementoALista(objetos, 'gorro de goleiro', 'dificil')
adicionarElementoALista(objetos, 'camisa térmica', 'dificil')
adicionarElementoALista(objetos, 'gelo spray', 'dificil')
adicionarElementoALista(objetos, 'faixa de capitão', 'dificil')
adicionarElementoALista(objetos, 'barreira móvel', 'dificil')
adicionarElementoALista(objetos, 'bola oficial da Copa', 'dificil')
adicionarElementoALista(objetos, 'taça de campeão', 'dificil')