import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const selecoes = []

adicionarElementoALista(selecoes, 'Brasil', 'facil')
adicionarElementoALista(selecoes, 'Alemanha', 'facil')
adicionarElementoALista(selecoes, 'Argentina', 'facil')
adicionarElementoALista(selecoes, 'França', 'facil')
adicionarElementoALista(selecoes, 'Itália', 'facil')
adicionarElementoALista(selecoes, 'Espanha', 'facil')
adicionarElementoALista(selecoes, 'Inglaterra', 'facil')
adicionarElementoALista(selecoes, 'Portugal', 'facil')
adicionarElementoALista(selecoes, 'Holanda', 'facil')
adicionarElementoALista(selecoes, 'Uruguai', 'facil')
adicionarElementoALista(selecoes, 'Croácia', 'medio')
adicionarElementoALista(selecoes, 'Bélgica', 'medio')
adicionarElementoALista(selecoes, 'Colômbia', 'medio')
adicionarElementoALista(selecoes, 'Chile', 'medio')
adicionarElementoALista(selecoes, 'México', 'medio')
adicionarElementoALista(selecoes, 'Suíça', 'medio')
adicionarElementoALista(selecoes, 'Suécia', 'medio')
adicionarElementoALista(selecoes, 'Dinamarca', 'medio')
adicionarElementoALista(selecoes, 'Nigéria', 'medio')
adicionarElementoALista(selecoes, 'Japão', 'medio')
adicionarElementoALista(selecoes, 'Islândia', 'dificil')
adicionarElementoALista(selecoes, 'Marrocos', 'dificil')
adicionarElementoALista(selecoes, 'Senegal', 'dificil')
adicionarElementoALista(selecoes, 'Peru', 'dificil')
adicionarElementoALista(selecoes, 'Irã', 'dificil')
adicionarElementoALista(selecoes, 'Coreia do Sul', 'dificil')
adicionarElementoALista(selecoes, 'Costa Rica', 'dificil')
adicionarElementoALista(selecoes, 'Gana', 'dificil')
adicionarElementoALista(selecoes, 'Camarões', 'dificil')
adicionarElementoALista(selecoes, 'Austrália', 'dificil')