import { adicionarElementoALista } from "./adicionarElementoALista.js"

export const tecnicos = []

adicionarElementoALista(tecnicos, 'Pep Guardiola', 'facil')
adicionarElementoALista(tecnicos, 'Jürgen Klopp', 'facil')
adicionarElementoALista(tecnicos, 'José Mourinho', 'facil')
adicionarElementoALista(tecnicos, 'Zinedine Zidane', 'facil')
adicionarElementoALista(tecnicos, 'Carlo Ancelotti', 'facil')
adicionarElementoALista(tecnicos, 'Diego Simeone', 'facil')
adicionarElementoALista(tecnicos, 'Tite', 'facil')
adicionarElementoALista(tecnicos, 'Luis Enrique', 'facil')
adicionarElementoALista(tecnicos, 'Didier Deschamps', 'facil')
adicionarElementoALista(tecnicos, 'Mauricio Pochettino', 'facil')
adicionarElementoALista(tecnicos, 'Roberto Mancini', 'medio')
adicionarElementoALista(tecnicos, 'Antonio Conte', 'medio')
adicionarElementoALista(tecnicos, 'Brendan Rodgers', 'medio')
adicionarElementoALista(tecnicos, 'Ernesto Valverde', 'medio')
adicionarElementoALista(tecnicos, 'Julian Nagelsmann', 'medio')
adicionarElementoALista(tecnicos, 'Marcelo Bielsa', 'medio')
adicionarElementoALista(tecnicos, 'Gareth Southgate', 'medio')
adicionarElementoALista(tecnicos, 'Fernando Santos', 'medio')
adicionarElementoALista(tecnicos, 'Thomas Tuchel', 'medio')
adicionarElementoALista(tecnicos, 'Jorge Jesus', 'medio')
adicionarElementoALista(tecnicos, 'Gian Piero Gasperini', 'dificil')
adicionarElementoALista(tecnicos, 'Unai Emery', 'dificil')
adicionarElementoALista(tecnicos, 'Julen Lopetegui', 'dificil')
adicionarElementoALista(tecnicos, 'Marco Rose', 'dificil')
adicionarElementoALista(tecnicos, 'Nuno Espírito Santo', 'dificil')
adicionarElementoALista(tecnicos, 'Lucien Favre', 'dificil')
adicionarElementoALista(tecnicos, 'Ralph Hasenhüttl', 'dificil')
adicionarElementoALista(tecnicos, 'Paulo Fonseca', 'dificil')
adicionarElementoALista(tecnicos, 'Hansi Flick', 'dificil')
adicionarElementoALista(tecnicos, 'Jesse Marsch', 'dificil')